[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 720, height = 600, color = [0, 0, 0, 120] }

    [entity.components.Transform]
    translation = { x = 360.0, y = 300.0 }
    depth = 1.0


[[entity]]

    [entity.components.Text]
    id = "cursor_resume"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 40.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 220, y = 400 }


[[entity]]

    [entity.components.Text]
    id = "cursor_main_menu"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 40.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 165, y = 300 }


[[entity]]

    [entity.components.Text]
    id = "cursor_exit"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 40.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 250, y = 200 }


[[entity]]

    [entity.components.Text]
    id = "resume"
    text = "RESUME"
    font_face = { font = "joystix", options.size = 40.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 400 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 220, height = 40 }

    [entity.components.Transform]
    translation = { x = 360.0, y = 400.0 }

    [entity.components.MouseReactive]
    id = "resume"


[[entity]]

    [entity.components.Text]
    id = "main_menu"
    text = "MAIN MENU"
    font_face = { font = "joystix", options.size = 40.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 300 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 310, height = 40 }

    [entity.components.Transform]
    translation = { x = 360.0, y = 300.0 }

    [entity.components.MouseReactive]
    id = "main_menu"


[[entity]]

    [entity.components.Text]
    id = "exit"
    text = "EXIT"
    font_face = { font = "joystix", options.size = 40.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 360, y = 200 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 150, height = 40 }

    [entity.components.Transform]
    translation = { x = 360.0, y = 200.0 }

    [entity.components.MouseReactive]
    id = "exit"
